version: 2.1

jobs:
  build:
    docker:
      - image: docker:git
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build
          command: docker build .

  publish:
    docker:
      - image: docker:git
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Publish
          command: |
            docker login --username $DOCKER_REGISTRY_USERNAME --password $DOCKER_REGISTRY_PASSWORD
            docker build --compress --tag compose:latest compose:$CIRCLE_TAG .
            docker push ddsoyka/compose:latest
            docker push ddsoyka/compose:$CIRCLE_TAG

workflows:
  version: 2
  development:
    jobs:
      - build
  publishing:
    jobs:
      - publish:
          filters:
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+$/
            branches:
              ignore: /^.*$/